// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vujaqbikjfkgdklugvkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1amFxYmlramZrZ2RrbHVndmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNDY4OTAsImV4cCI6MjA4NDgyMjg5MH0.6Tx7kAUaCPFZMqt-Y771mYRsR9x_HPFFQknjRnPOlpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});